### ISSUE TITLE
Move api endpoint access to .env

### ISSUE THREAD

**Issue by ssoerensen** [GAIA-X4PLC-AAD/portal#22]
Hard coded in: src/services/ApiService.tsx
config var needs to be used like this: process.env.REACT_APP_$(YOUR_VAR)

e.g. const endpoint = "https://fc-server.gxfs.gx4fm.org/query";
        const endpoint = "https://fc-server.gxfs.gx4fm.org/schemas/latest?type=shape";

**Comment by raze-sag** [comment]
Maybe you could check out my PR #103 in which I have moved the endpoints to the .env file

**Comment by devbysp** [comment]
## Pull Request

- https://github.com/GAIA-X4PLC-AAD/portal/pull/103

solved by: @raze-sag see [comment](https://github.com/GAIA-X4PLC-AAD/portal/issues/22#issuecomment-2373227644)
