### ISSUE TITLE
Rework search Page Resources: Filter based on values from shape

### ISSUE THREAD

**Issue by lenasauermann** [GAIA-X4PLC-AAD/portal#82]
Right now the filter values are hard-coded. The goal is to get the values for the filter options dynamically from the shacl shpaes

**Comment by lenasauermann** [comment]
For type we should use all classes for the ontology that have DataResource as a subClass

For Format we need to look in the properties of the shacl shapes that describe these classes

**Comment by lenasauermann** [comment]
For type we could also the distinct list of labels from the Cipher Query

**Comment by devbysp** [comment]
## Pull Requests

- portal: [https://github.com/GAIA-X4PLC-AAD/portal/pull/95](https://github.com/GAIA-X4PLC-AAD/portal/pull/95)

**Comment by devbysp** [comment]
## Pull Request 2
- 

### Required
-

### Other thing solved
- Type filter modified
   - the node labels should contain at least one of the selected filters
   - the node labels should contain the `DataResource` label too
   - only main nodes (uri which does not start with `pnode://`) are returned as result.

```typescript 
 /**
   * Returns all resources of type included in the type asset list passed in as parameter.
   *
   * @param authContext authorization token for server calls
   * @param typeFilters the list of requested resource types
   */
  async getAllResources(authContext: AuthContextType, typeFilters: Asset[]): Promise<ResourceInput> {
    const whereClause = typeFilters.length ?
      `WHERE ANY (label IN labels(n) WHERE label IN [ '${typeFilters.join('\', \'')}'])
       AND 'DataResource' IN labels(n)
       AND NOT n.uri STARTS WITH 'bnode://'`
      : ''

    return cypherQuery(authContext, {
      statement: `MATCH (n) ${whereClause} RETURN properties(n) AS properties, labels(n) AS labels`,
    })
  }
```

- Code cleanup: Resource, ResourceInput, ServiceOffering, ServiceOfferingInput were simplified and moved to the correct files.
- Fetching resource types simplified: see the [comment](https://github.com/GAIA-X4PLC-AAD/portal/issues/82#issuecomment-2283525932)

**Comment by devbysp** [comment]
## Pull Request 3
- ... in progress

### Required
- Rendering _**vendor**_ filters dynamically from fetched resources. The vendor information is stored in a linked node referred by the `copyrightOwnedBy` property.
