### ISSUE TITLE
Rework search page resources: show all resources, not only HDMaps, Scenarios, etc.

### ISSUE THREAD

**Issue by lenasauermann** [GAIA-X4PLC-AAD/portal#84]
The portal was modified for the Hannover fair to only show specific resources. Instead it should now show all DataResources.

DataResource is a label based on Gaia-X which will be the base label of all domain specific resource.

**Comment by lenasauermann** [comment]
/query?withTotalCount=false --> to turn off the addition of "WITH count(*) as totalCount" to avoid errors

Body:
{ "statement":"MATCH (n:HdMap)-[r*0..3]->(m) WITH n, labels(m) AS m_labels, properties(m) AS m_properties RETURN properties(n) AS n_properties, labels(n) AS n_labels, COLLECT({labels: m_labels, properties: m_properties}) AS m_data ORDER BY n_properties"}

**Comment by lenasauermann** [comment]
https://www.figma.com/design/l5S4jVTtfCgE3Qb9oSTk9z/Gaia-X-Portal-Wireframe?node-id=483-1398&t=CIqFiuQV5t9WhZZz-0

**Comment by lenasauermann** [comment]
Covered with this task: https://github.com/GAIA-X4PLC-AAD/portal/pull/101

**Comment by devbysp** [comment]
This issue has been solved in this taskk: [Rework search Page Resources: Filter based on values from shape](https://github.com/GAIA-X4PLC-AAD/portal/issues/82)

## Note
- The resources have been fetched using the cypher query mentioned in this [comment](https://github.com/GAIA-X4PLC-AAD/portal/issues/82#issuecomment-2330706486)
